CREATE TABLE "listing_media" (
	"media_key" text PRIMARY KEY NOT NULL,
	"listing_id" text,
	"media_type" text,
	"media_category" text,
	"media_url" text,
	"media_status" text,
	"image_height" integer,
	"image_width" integer,
	"is_preferred" boolean DEFAULT false,
	"display_order" integer,
	"short_description" text,
	"modification_timestamp" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "listings" (
	"id" text PRIMARY KEY NOT NULL,
	"unparsed_address" text,
	"street_number" text,
	"street_name" text,
	"street_suffix" text,
	"unit_number" text,
	"city" text,
	"province" text,
	"postal_code" text,
	"country" text,
	"county_or_parish" text,
	"latitude" double precision,
	"longitude" double precision,
	"geo_source" text,
	"property_type" text,
	"property_sub_type" text,
	"transaction_type" text,
	"contract_status" text,
	"building_name" text,
	"year_built" integer,
	"lot_size_area" double precision,
	"lot_size_units" text,
	"living_area" double precision,
	"above_grade_finished_area" double precision,
	"below_grade_finished_area" double precision,
	"lot_width" double precision,
	"lot_depth" double precision,
	"lot_frontage" text,
	"bedrooms_total" integer,
	"bedrooms_above_grade" integer,
	"bedrooms_below_grade" integer,
	"bathrooms_total" integer,
	"kitchens_total" integer,
	"rooms_total" integer,
	"interior_features" text[],
	"exterior_features" text[],
	"parking_features" text[],
	"water_features" text[],
	"zoning" text,
	"business_type" text[],
	"list_price" numeric,
	"original_list_price" numeric,
	"close_price" numeric,
	"association_fee" numeric,
	"tax_annual_amount" numeric,
	"tax_year" integer,
	"media_keys" text[],
	"preferred_media_key" text,
	"virtual_tour_url" text,
	"public_remarks" text,
	"private_remarks" text,
	"tax_legal_description" text,
	"directions" text,
	"list_date" timestamp,
	"expiration_date" timestamp,
	"close_date" timestamp,
	"standard_status" text,
	"modification_timestamp" timestamp,
	"originating_system_id" text,
	"originating_system_name" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"raw" jsonb
);
--> statement-breakpoint
CREATE TABLE "replication_state" (
	"id" integer PRIMARY KEY NOT NULL,
	"resource_name" text NOT NULL,
	"last_timestamp" text NOT NULL,
	"last_key" text NOT NULL,
	"records_processed" integer DEFAULT 0,
	"last_run_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "listing_media" ADD CONSTRAINT "listing_media_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE cascade ON UPDATE no action;